export { default as Trainee } from './Trainee'
export { default as TraineeList } from './TraineeList'
export { default as TraineeDetail } from './TraineeDetail'
export { default as GetTrainee } from './GetTrainee'
export { default as UserMe } from './UserMe'
export { default as UpdateTrainee } from './UpdateTrainee'
export { default as DeleteTrainee } from './DeleteTrainee'